# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    # Build the app
    build_ios_app(
      scheme: "Cheffy",
      configuration: "Release",
      export_method: "app-store",
      export_options: {
        method: "app-store",
        uploadBitcode: false,
        uploadSymbols: true,
        compileBitcode: false
      }
    )
    
    # Upload to TestFlight
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end

  desc "Build and upload to App Store"
  lane :release do
    # Build the app
    build_ios_app(
      scheme: "Cheffy",
      configuration: "Release",
      export_method: "app-store",
      export_options: {
        method: "app-store",
        uploadBitcode: false,
        uploadSymbols: true,
        compileBitcode: false
      }
    )
    
    # Upload to App Store
    upload_to_app_store(
      skip_metadata: true,
      skip_screenshots: true,
      precheck_include_in_app_purchases: false
    )
  end

  desc "Build for development"
  lane :build_dev do
    build_ios_app(
      scheme: "Cheffy",
      configuration: "Debug",
      export_method: "development"
    )
  end

  desc "Build for ad-hoc distribution"
  lane :build_adhoc do
    build_ios_app(
      scheme: "Cheffy",
      configuration: "Release",
      export_method: "ad-hoc"
    )
  end

  desc "Setup certificates and provisioning profiles"
  lane :setup_certificates do
    match(
      type: "development",
      readonly: true
    )
    
    match(
      type: "appstore",
      readonly: true
    )
  end

  desc "Update provisioning profiles"
  lane :update_profiles do
    match(
      type: "development",
      force_for_new_devices: true
    )
    
    match(
      type: "appstore",
      force_for_new_devices: true
    )
  end
end 